## Import Library | pandas | numpy

In [83]:
import numpy as np
import pandas as pd

# Import Datasets

In [84]:
df = pd.read_csv('customer.csv')

In [85]:
df.sample(5)

    age  gender   review education purchased
20   57  Female  Average    School       Yes
3    72  Female     Good        PG        No
42   30  Female     Good        PG       Yes
14   15    Male     Poor        PG       Yes
33   89  Female     Good        PG       Yes

## Eliminate Unnecessary Columns

In [86]:
df = df.iloc[:,2:]

In [87]:
df.sample(5)

     review education purchased
3      Good        PG        No
16     Poor        UG       Yes
24  Average        PG       Yes
10     Good        UG       Yes
48     Good        UG       Yes

## Train_Test_Split

In [88]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/arjan/env/lib/python3.8/site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /Users/arjan/env/lib/python3.8/site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: scipy>=1.5.0 in /Users/arjan/env/lib/python3.8/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /Users/arjan/env/lib/python3.8/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/arjan/env/lib/python3.8/site-packages (from scikit-learn) (3.5.0)

In [49]:
from sklearn.model_selection import train_test_split

In [89]:
import sys
print(sys.executable)

/Users/arjan/env/bin/python

In [90]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1:],test_size=0.2)

## Import_OrdinalEncoder

In [91]:
from sklearn.preprocessing import OrdinalEncoder

In [92]:
x_train

     review education
37  Average        PG
2      Good        PG
49     Good        UG
11     Good        UG
44  Average        UG
19     Poor        PG
0   Average    School
47     Good        PG
41     Good        PG
35     Poor    School
29  Average        UG
45     Poor        PG
21  Average        PG
8   Average        UG
48     Good        UG
30  Average        UG
15     Poor        UG
42     Good        PG
20  Average    School
12     Poor    School
38     Good    School
13  Average    School
1      Poor        UG
25     Good    School
34  Average    School
24  Average        PG
3      Good        PG
22     Poor        PG
16     Poor        UG
46     Poor        PG
31     Poor    School
27     Poor        PG
17     Poor        UG
36     Good        UG
43     Poor        PG
6      Good    School
40     Good    School
32  Average        UG
10     Good        UG
28     Poor    School

## Define Categories

In [93]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [94]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

## Transform Ordinal Encoding

In [95]:
x_train = oe.transform(x_train) 
x_test = oe.transform(x_test)

In [57]:
x_train

array([[0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.]])

In [96]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding

In [97]:
from sklearn.preprocessing import LabelEncoder

In [98]:
le = LabelEncoder()

In [99]:
le.fit(y_train) # Fit LabelEncoder only on y_train (without all possible labels)

/Users/arjan/env/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [100]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [101]:
y_train = le.transform(y_train) 
y_test = le.transform(y_test)

/Users/arjan/env/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/arjan/env/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [102]:
y_train

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0])