# KNN Imputer

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.impute import KNNImputer,SimpleImputer 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

# Import Dataset

In [3]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [6]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

# Check Missing Value

In [9]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

# Define X & Y

In [10]:
X = df.drop(columns=['Survived']) 
y = df['Survived']

# Train Test Split

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [31]:
X_train

      Age  Pclass      Fare
30   40.0       1   27.7208
10    4.0       3   16.7000
873  47.0       3    9.0000
182   9.0       3   31.3875
876  20.0       3    9.8458
..    ...     ...       ...
534  30.0       3    8.6625
584   NaN       3    8.7125
493  71.0       1   49.5042
527   NaN       1  221.7792
168   NaN       1   25.9250

[712 rows x 3 columns]

# Apply KNN Imputer

In [32]:
knn = KNNImputer(n_neighbors = 10, weights ='distance') 
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

# Convert in Data Frame

In [33]:
pd.DataFrame(X_train_trf, columns = X_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  25.118926     3.0    8.7125
709  71.000000     1.0   49.5042
710  31.125155     1.0  221.7792
711  49.200824     1.0   25.9250

[712 rows x 3 columns]

In [44]:
pd.DataFrame(X_train_trf,columns = X_train.columns).sample(10)

      Age  Pclass     Fare
588  45.0     1.0  26.5500
137  42.0     2.0  26.0000
679  29.0     3.0  15.2458
289  36.0     2.0  12.8750
96   41.0     3.0  39.6875
504  29.0     2.0  26.0000
277  27.0     2.0  21.0000
368  25.0     2.0  41.5792
640  13.0     2.0  19.5000
266  33.7     3.0   8.0500

# Apply Logistic Regression

In [46]:
lr = LogisticRegression() 

lr.fit(X_train_trf,y_train) 

y_pred = lr.predict(X_test_trf) 

accuracy_score(y_test,y_pred)

0.7039106145251397